ADMIN_QUEUE_NAME = "smc_tg_admin_panel"
DEFAULT_ADMIN_ENDPOINT = "/api/v1/admin"

KEYBOARD_BUTTON_TYPE_LINK = "LINK"

TELEGRAM_FIELD_REPLY_MARKUP = "reply_markup"
TELEGRAM_FIELD_INLINE_KEYBOARD = "inline_keyboard"
TELEGRAM_FIELD_KEYBOARD = "keyboard"
TELEGRAM_FIELD_RESIZE_KEYBOARD = "resize_keyboard"
TELEGRAM_FIELD_ONE_TIME_KEYBOARD = "one_time_keyboard"
TELEGRAM_FIELD_CALLBACK_DATA = "callback_data"
TELEGRAM_FIELD_TEXT = "text"
TELEGRAM_FIELD_URL = "url"
TELEGRAM_FIELD_STYLE = "style"

TELEGRAM_BUTTON_STYLE_DANGER = "danger"
TELEGRAM_BUTTON_STYLE_SUCCESS = "success"
TELEGRAM_BUTTON_STYLE_PRIMARY = "primary"

TELEGRAM_BUTTON_COLOR_TO_STYLE = {
    TELEGRAM_BUTTON_STYLE_DANGER: TELEGRAM_BUTTON_STYLE_DANGER,
    "red": TELEGRAM_BUTTON_STYLE_DANGER,
    "красный": TELEGRAM_BUTTON_STYLE_DANGER,
    "#f44336": TELEGRAM_BUTTON_STYLE_DANGER,
    "#ff0000": TELEGRAM_BUTTON_STYLE_DANGER,
    TELEGRAM_BUTTON_STYLE_SUCCESS: TELEGRAM_BUTTON_STYLE_SUCCESS,
    "green": TELEGRAM_BUTTON_STYLE_SUCCESS,
    "зеленый": TELEGRAM_BUTTON_STYLE_SUCCESS,
    "зелёный": TELEGRAM_BUTTON_STYLE_SUCCESS,
    "#4caf50": TELEGRAM_BUTTON_STYLE_SUCCESS,
    "#00ff00": TELEGRAM_BUTTON_STYLE_SUCCESS,
    TELEGRAM_BUTTON_STYLE_PRIMARY: TELEGRAM_BUTTON_STYLE_PRIMARY,
    "blue": TELEGRAM_BUTTON_STYLE_PRIMARY,
    "синий": TELEGRAM_BUTTON_STYLE_PRIMARY,
    "#2196f3": TELEGRAM_BUTTON_STYLE_PRIMARY,
    "#0000ff": TELEGRAM_BUTTON_STYLE_PRIMARY,
}
